jdbc:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ai_code_generator
  username: root
  password: 123456
  host: localhost
  port: 3306
  database: ai_code_generator